### ISSUE TITLE
kepler-exporter-lvr6f in CrashLoopBackOff

### ISSUE THREAD

**Issue by jichenjc** [sustainable-computing-io/kepler#130]
install from https://www.youtube.com/watch?v=P5weULiBl60
on a kind container.. got following error

```
# kubectl logs kepler-exporter-lvr6f -n monitoring
2022/09/05 03:33:36 InitSliceHandler: &{map[] /sys/fs/cgroup/cpu /sys/fs/cgroup/memory /sys/fs/cgroup/blkio}
cpu architecture Haswell, dram in GB 62
use power estimate to obtain power
2022/09/05 03:33:36 Available counter metrics: [cpu_cycles cpu_instr cache_miss]
2022/09/05 03:33:36 Available cgroup metrics: []
2022/09/05 03:33:36 Available kubelet metrics: [container_cpu_usage_seconds_total container_memory_working_set_bytes]
2022/09/05 03:33:36 set coreMetricIndex = 1
2022/09/05 03:33:36 set generalMetricIndex = 1
2022/09/05 03:33:36 set dramMetricIndex = 3
config EnabledEBPFCgroupID enabled:  true
config getKernelVersion:  4.15
config set EnabledEBPFCgroupID to  false
modprobe: FATAL: Module kheaders not found in directory /lib/modules/4.15.0-20-generic
chdir(/lib/modules/4.15.0-20-generic/build): No such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x812ad6]

goroutine 1 [running]:
github.com/iovisor/gobpf/bcc.(*Module).Load(0x0, {0xd3706f, 0xc}, 0x2?, 0x2?, 0xc0000ddc58?)
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/vendor/github.com/iovisor/gobpf/bcc/module.go:202 +0x36
github.com/iovisor/gobpf/bcc.(*Module).LoadTracepoint(...)
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/vendor/github.com/iovisor/gobpf/bcc/module.go:182
github.com/sustainable-computing-io/kepler/pkg/attacher.loadModule({0x15c0200?, 0xd35bc9?, 0xc000599a40?}, {0xc000237b00, 0x2, 0x2})
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/attacher/bcc_attacher.go:63 +0x94
github.com/sustainable-computing-io/kepler/pkg/attacher.AttachBPFAssets()
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/attacher/bcc_attacher.go:104 +0x25d
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Attach(0xc000227eb0)
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/collector.go:96 +0x25
main.main()
        /opt/app-root/src/github.com/sustainable-computing-io/kepler/cmd/exporter.go:67 +0x23a
```

**Comment by jichenjc** [comment]
looks like `/lib/modules/4.15.0-20-generic` is missing..
so some kind of doc need to be updated

**Comment by jichenjc** [comment]
found the root cause, sorry for confusion
