### ISSUE TITLE
Segfault from commit e0ec4fddc3fdcc7e8de18e9e494806fb9a8659b2

### ISSUE THREAD

**Issue by maryamtahhan** [sustainable-computing-io/kepler#1454]
### What happened?

`chore(bpfassets): Refactor to reduce the API exposed by bpfassets` (#1413) seems to cause a segfault when running Kepler. The error is shown below. 

I used git bisect to determine the offending commit. 

to reproduce:

- use `make build` to build Kepler.
- then `echo -n "true" > ./_output/ENABLE_PROCESS_METRICS` then try to run kepler locally on my server as shown below:

```
[root@3e5ef333d785 kepler]# _output/bin/kepler -enable-gpu=true -v "8" &
[1] 47014
[root@3e5ef333d785 kepler]# I0520 14:20:16.194567   47014 gpu.go:38] Trying to initialize GPU collector using dcgm
W0520 14:20:16.194706   47014 gpu_dcgm.go:104] There is no DCGM daemon running in the host: libdcgm.so not Found
W0520 14:20:16.194722   47014 gpu_dcgm.go:108] Could not start DCGM. Error: libdcgm.so not Found
I0520 14:20:16.194728   47014 gpu.go:45] Error initializing dcgm: not able to connect to DCGM: libdcgm.so not Found
I0520 14:20:16.194737   47014 gpu.go:38] Trying to initialize GPU collector using nvidia-nvml
I0520 14:20:16.194761   47014 gpu.go:45] Error initializing nvidia-nvml: failed to init nvml. ERROR_LIBRARY_NOT_FOUND
I0520 14:20:16.194764   47014 gpu.go:38] Trying to initialize GPU collector using habana
I0520 14:20:16.194768   47014 gpu.go:42] Using habana to obtain gpu power
E0520 14:20:16.194823   47014 utils.go:167] cpuid command start failure: exec: "cpuid": executable file not found in $PATH
E0520 14:20:16.194837   47014 utils.go:265] failed to read cpus.yaml: open /var/lib/kepler/data/cpus.yaml: no such file or directory
E0520 14:20:16.194841   47014 utils.go:139] getCPUArch failure: open /var/lib/kepler/data/cpus.yaml: no such file or directory
I0520 14:20:16.196966   47014 exporter.go:85] Kepler running on version: e0ec4fdd
I0520 14:20:16.196978   47014 config.go:283] using gCgroup ID in the BPF program: true
I0520 14:20:16.196996   47014 config.go:285] kernel version: 5.14
I0520 14:20:16.197031   47014 config.go:310] The Idle power will be exposed. Are you running on Baremetal or using single VM per node?
I0520 14:20:16.197036   47014 config.go:151] ENABLE_EBPF_CGROUPID: true
I0520 14:20:16.197039   47014 config.go:152] ENABLE_GPU: true
I0520 14:20:16.197042   47014 config.go:153] ENABLE_QAT: false
I0520 14:20:16.197046   47014 config.go:154] ENABLE_PROCESS_METRICS: false
I0520 14:20:16.197050   47014 config.go:155] EXPOSE_HW_COUNTER_METRICS: true
I0520 14:20:16.197054   47014 config.go:156] EXPOSE_CGROUP_METRICS: true
I0520 14:20:16.197058   47014 config.go:157] EXPOSE_IRQ_COUNTER_METRICS: true
I0520 14:20:16.197062   47014 config.go:158] EXPOSE_ESTIMATED_IDLE_POWER_METRICS: true. This only impacts when the power is estimated using pre-prained models. Estimated idle power is meanin
gful only when Kepler is running on bare-metal or with a single virtual machine (VM) on the node.
I0520 14:20:16.197069   47014 config.go:159] EXPERIMENTAL_BPF_SAMPLE_RATE: 0
I0520 14:20:16.197093   47014 power.go:53] use sysfs to obtain power
I0520 14:20:16.197099   47014 redfish.go:169] failed to get redfish credential file path
I0520 14:20:16.199811   47014 acpi.go:69] Using the ACPI power meter path: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI000D:00/
I0520 14:20:16.199817   47014 power.go:73] using acpi to obtain power
I0520 14:20:16.219855   47014 attacher.go:140] found bpf object file: bpfassets/libbpf/bpf.o/kepler.bpfel.o
libbpf: loading bpfassets/libbpf/bpf.o/kepler.bpfel.o
libbpf: elf: section(3) tp/sched/sched_switch, size 1864, link 0, flags 6, type=1
libbpf: sec 'tp/sched/sched_switch': found program 'kepler_sched_switch_trace' at insn offset 0 (0 bytes), code size 233 insns (1864 bytes)
libbpf: elf: section(4) .reltp/sched/sched_switch, size 288, link 32, flags 40, type=9
libbpf: elf: section(5) tp/irq/softirq_entry, size 144, link 0, flags 6, type=1
libbpf: sec 'tp/irq/softirq_entry': found program 'kepler_irq_trace' at insn offset 0 (0 bytes), code size 18 insns (144 bytes)
libbpf: elf: section(6) .reltp/irq/softirq_entry, size 16, link 32, flags 40, type=9
libbpf: elf: section(7) fexit/mark_page_accessed, size 104, link 0, flags 6, type=1
libbpf: sec 'fexit/mark_page_accessed': found program 'kepler_read_page_trace' at insn offset 0 (0 bytes), code size 13 insns (104 bytes)
libbpf: elf: section(8) .relfexit/mark_page_accessed, size 16, link 32, flags 40, type=9
libbpf: elf: section(9) tp/writeback/writeback_dirty_folio, size 104, link 0, flags 6, type=1
libbpf: sec 'tp/writeback/writeback_dirty_folio': found program 'kepler_write_page_trace' at insn offset 0 (0 bytes), code size 13 insns (104 bytes)
libbpf: elf: section(10) .reltp/writeback/writeback_dirty_folio, size 16, link 32, flags 40, type=9
libbpf: elf: section(11) .rodata.config, size 12, link 0, flags 2, type=1
libbpf: elf: section(12) .bss, size 4, link 0, flags 3, type=8
libbpf: elf: section(13) .maps, size 352, link 0, flags 3, type=1
libbpf: elf: section(14) license, size 13, link 0, flags 3, type=1
libbpf: license of bpfassets/libbpf/bpf.o/kepler.bpfel.o is Dual BSD/GPL
libbpf: elf: section(23) .BTF, size 5656, link 0, flags 0, type=1
libbpf: elf: section(25) .BTF.ext, size 2072, link 0, flags 0, type=1
libbpf: elf: section(32) .symtab, size 1128, link 1, flags 0, type=2
libbpf: looking for externs among 47 symbols...
libbpf: collected 0 externs total
libbpf: map 'processes': at sec_idx 13, offset 0.
libbpf: map 'processes': found type = 1.
libbpf: map 'processes': found key [6], sz = 4.
libbpf: map 'processes': found value [10], sz = 112.
libbpf: map 'processes': found max_entries = 32768.
libbpf: map 'pid_time': at sec_idx 13, offset 32.
libbpf: map 'pid_time': found type = 1.
libbpf: map 'pid_time': found key [6], sz = 4.
libbpf: map 'pid_time': found value [12], sz = 8.
libbpf: map 'pid_time': found max_entries = 32768.
libbpf: map 'cpu_cycles_event_reader': at sec_idx 13, offset 64.
libbpf: map 'cpu_cycles_event_reader': found type = 4.
libbpf: map 'cpu_cycles_event_reader': found key [2], sz = 4.
libbpf: map 'cpu_cycles_event_reader': found value [6], sz = 4.
libbpf: map 'cpu_cycles_event_reader': found max_entries = 128.
libbpf: map 'cpu_cycles': at sec_idx 13, offset 96.
libbpf: map 'cpu_cycles': found type = 2.
libbpf: map 'cpu_cycles': found key [6], sz = 4.
libbpf: map 'cpu_cycles': found value [12], sz = 8.
libbpf: map 'cpu_cycles': found max_entries = 128.
libbpf: map 'cpu_instructions_event_reader': at sec_idx 13, offset 128.
libbpf: map 'cpu_instructions_event_reader': found type = 4.
libbpf: map 'cpu_instructions_event_reader': found key [2], sz = 4.
libbpf: map 'cpu_instructions_event_reader': found value [6], sz = 4.
libbpf: map 'cpu_instructions_event_reader': found max_entries = 128.
libbpf: map 'cpu_instructions': at sec_idx 13, offset 160.
libbpf: map 'cpu_instructions': found type = 2.
libbpf: map 'cpu_instructions': found key [6], sz = 4.
libbpf: map 'cpu_instructions': found value [12], sz = 8.
libbpf: map 'cpu_instructions': found max_entries = 128.
libbpf: map 'cache_miss_event_reader': at sec_idx 13, offset 192.
libbpf: map 'cache_miss_event_reader': found type = 4.
libbpf: map 'cache_miss_event_reader': found key [2], sz = 4.
libbpf: map 'cache_miss_event_reader': found value [6], sz = 4.
libbpf: map 'cache_miss_event_reader': found max_entries = 128.
libbpf: map 'cache_miss': at sec_idx 13, offset 224.
libbpf: map 'cache_miss': found type = 2.
libbpf: map 'cache_miss': found key [6], sz = 4.
libbpf: map 'cache_miss': found value [12], sz = 8.
libbpf: map 'cache_miss': found max_entries = 128.
libbpf: map 'task_clock_ms_event_reader': at sec_idx 13, offset 256.
libbpf: map 'task_clock_ms_event_reader': found type = 4.
libbpf: map 'task_clock_ms_event_reader': found key [2], sz = 4.
libbpf: map 'task_clock_ms_event_reader': found value [6], sz = 4.
libbpf: map 'task_clock_ms_event_reader': found max_entries = 128.
libbpf: map 'task_clock': at sec_idx 13, offset 288.
libbpf: map 'task_clock': found type = 2.
libbpf: map 'task_clock': found key [6], sz = 4.
libbpf: map 'task_clock': found value [12], sz = 8.
libbpf: map 'task_clock': found max_entries = 128.
libbpf: map 'cpu_freq_array': at sec_idx 13, offset 320.
libbpf: map 'cpu_freq_array': found type = 2.
libbpf: map 'cpu_freq_array': found key [6], sz = 4.
libbpf: map 'cpu_freq_array': found value [6], sz = 4.
libbpf: map 'cpu_freq_array': found max_entries = 128.
libbpf: map '.rodata.config' (global data): at sec_idx 11, offset 0, flags 80.
libbpf: map 11 is ".rodata.config"
libbpf: map 'kepler.bss' (global data): at sec_idx 12, offset 0, flags 400.
libbpf: map 12 is "kepler.bss"
libbpf: sec '.reltp/sched/sched_switch': collecting relocation for section(3) 'tp/sched/sched_switch'
libbpf: sec '.reltp/sched/sched_switch': relo #0: insn #0 against '.rodata.config'
libbpf: prog 'kepler_sched_switch_trace': found data map 11 (.rodata.config, sec 11, off 0) for insn 0
libbpf: sec '.reltp/sched/sched_switch': relo #1: insn #7 against 'counter_sched_switch'
libbpf: prog 'kepler_sched_switch_trace': found data map 12 (kepler.bss, sec 12, off 0) for insn 7
libbpf: sec '.reltp/sched/sched_switch': relo #2: insn #16 against '.rodata.config'
libbpf: prog 'kepler_sched_switch_trace': found data map 11 (.rodata.config, sec 11, off 0) for insn 16
libbpf: sec '.reltp/sched/sched_switch': relo #3: insn #41 against 'cpu_cycles_event_reader'
libbpf: prog 'kepler_sched_switch_trace': found map 2 (cpu_cycles_event_reader, sec 13, off 64) for insn #41
libbpf: sec '.reltp/sched/sched_switch': relo #4: insn #53 against 'cpu_cycles'
libbpf: prog 'kepler_sched_switch_trace': found map 3 (cpu_cycles, sec 13, off 96) for insn #53
libbpf: sec '.reltp/sched/sched_switch': relo #5: insn #67 against 'cpu_cycles'
libbpf: prog 'kepler_sched_switch_trace': found map 3 (cpu_cycles, sec 13, off 96) for insn #67
libbpf: sec '.reltp/sched/sched_switch': relo #6: insn #77 against 'cpu_instructions_event_reader'
libbpf: prog 'kepler_sched_switch_trace': found map 4 (cpu_instructions_event_reader, sec 13, off 128) for insn #77
libbpf: sec '.reltp/sched/sched_switch': relo #7: insn #87 against 'cpu_instructions'
libbpf: prog 'kepler_sched_switch_trace': found map 5 (cpu_instructions, sec 13, off 160) for insn #87
libbpf: sec '.reltp/sched/sched_switch': relo #8: insn #99 against 'cpu_instructions'
libbpf: prog 'kepler_sched_switch_trace': found map 5 (cpu_instructions, sec 13, off 160) for insn #99
libbpf: sec '.reltp/sched/sched_switch': relo #9: insn #111 against 'cache_miss_event_reader'
libbpf: prog 'kepler_sched_switch_trace': found map 6 (cache_miss_event_reader, sec 13, off 192) for insn #111
libbpf: sec '.reltp/sched/sched_switch': relo #10: insn #122 against 'cache_miss'
libbpf: prog 'kepler_sched_switch_trace': found map 7 (cache_miss, sec 13, off 224) for insn #122
libbpf: sec '.reltp/sched/sched_switch': relo #11: insn #136 against 'cache_miss'
libbpf: prog 'kepler_sched_switch_trace': found map 7 (cache_miss, sec 13, off 224) for insn #136
libbpf: sec '.reltp/sched/sched_switch': relo #12: insn #145 against 'pid_time'
libbpf: prog 'kepler_sched_switch_trace': found map 1 (pid_time, sec 13, off 32) for insn #145
libbpf: sec '.reltp/sched/sched_switch': relo #13: insn #153 against 'pid_time'
libbpf: prog 'kepler_sched_switch_trace': found map 1 (pid_time, sec 13, off 32) for insn #153
libbpf: sec '.reltp/sched/sched_switch': relo #14: insn #165 against 'pid_time'
libbpf: prog 'kepler_sched_switch_trace': found map 1 (pid_time, sec 13, off 32) for insn #165
libbpf: sec '.reltp/sched/sched_switch': relo #15: insn #171 against 'processes'
libbpf: prog 'kepler_sched_switch_trace': found map 0 (processes, sec 13, off 0) for insn #171
libbpf: sec '.reltp/sched/sched_switch': relo #16: insn #195 against 'processes'
libbpf: prog 'kepler_sched_switch_trace': found map 0 (processes, sec 13, off 0) for insn #195
libbpf: sec '.reltp/sched/sched_switch': relo #17: insn #227 against 'processes'
libbpf: prog 'kepler_sched_switch_trace': found map 0 (processes, sec 13, off 0) for insn #227
libbpf: sec '.reltp/irq/softirq_entry': collecting relocation for section(5) 'tp/irq/softirq_entry'
libbpf: sec '.reltp/irq/softirq_entry': relo #0: insn #6 against 'processes'
libbpf: prog 'kepler_irq_trace': found map 0 (processes, sec 13, off 0) for insn #6
libbpf: sec '.relfexit/mark_page_accessed': collecting relocation for section(7) 'fexit/mark_page_accessed'
libbpf: sec '.relfexit/mark_page_accessed': relo #0: insn #4 against 'processes'
libbpf: prog 'kepler_read_page_trace': found map 0 (processes, sec 13, off 0) for insn #4
libbpf: sec '.reltp/writeback/writeback_dirty_folio': collecting relocation for section(9) 'tp/writeback/writeback_dirty_folio'
libbpf: sec '.reltp/writeback/writeback_dirty_folio': relo #0: insn #4 against 'processes'
libbpf: prog 'kepler_write_page_trace': found map 0 (processes, sec 13, off 0) for insn #4
I0520 14:20:16.220404   47014 attacher.go:158] 160 CPU cores detected. Resizing eBPF Perf Event Arrays
libbpf: object 'kepler': failed (-22) to create BPF token from '/sys/fs/bpf', skipping optional step...
libbpf: loaded kernel BTF from '/sys/kernel/btf/vmlinux'
libbpf: map 'processes': created successfully, fd=8
libbpf: map 'pid_time': created successfully, fd=9
libbpf: map 'cpu_cycles_event_reader': created successfully, fd=10
libbpf: map 'cpu_cycles': created successfully, fd=11
libbpf: map 'cpu_instructions_event_reader': created successfully, fd=12
libbpf: map 'cpu_instructions': created successfully, fd=13
libbpf: map 'cache_miss_event_reader': created successfully, fd=14
libbpf: map 'cache_miss': created successfully, fd=15
libbpf: map 'task_clock_ms_event_reader': created successfully, fd=16
libbpf: map 'task_clock': created successfully, fd=17
libbpf: map 'cpu_freq_array': created successfully, fd=18
libbpf: map '.rodata.config': created successfully, fd=19
libbpf: map 'kepler.bss': created successfully, fd=20
libbpf: failed to open '/sys/kernel/tracing/events/sched/sched_switch/id': No such file or directory
libbpf: failed to determine tracepoint 'sched/sched_switch' perf event ID: No such file or directory
libbpf: prog 'kepler_sched_switch_trace': failed to create tracepoint 'sched/sched_switch' perf event: No such file or directory
I0520 14:20:16.233639   47014 attacher.go:186] failed to attach tracepoint/sched/sched_switch: failed to attach program: no such file or directory
libbpf: failed to open '/sys/kernel/tracing/events/irq/softirq_entry/id': No such file or directory
libbpf: failed to determine tracepoint 'irq/softirq_entry' perf event ID: No such file or directory
libbpf: prog 'kepler_irq_trace': failed to create tracepoint 'irq/softirq_entry' perf event: No such file or directory
W0520 14:20:16.233660   47014 attacher.go:200] could not attach irq/softirq_entry: failed to attach program: no such file or directory
libbpf: failed to open '/sys/kernel/tracing/events/writeback/writeback_dirty_folio/id': No such file or directory
libbpf: failed to determine tracepoint 'writeback/writeback_dirty_folio' perf event ID: No such file or directory
libbpf: prog 'kepler_write_page_trace': failed to create tracepoint 'writeback/writeback_dirty_folio' perf event: No such file or directory
W0520 14:20:16.233679   47014 attacher.go:215] failed to attach tp/writeback/writeback_dirty_folio: failed to attach tracepoint writeback_dirty_folio to program kepler_write_page_trace: no s
uch file or directory. Kepler will not collect page cache write events. This will affect the DRAM power model estimation on VMs.
I0520 14:20:16.279749   47014 attacher.go:270] Successfully load eBPF module from libbpf object
I0520 14:20:16.279768   47014 utils.go:85] Available ebpf software counters: [bpf_net_tx_irq bpf_net_rx_irq bpf_block_irq bpf_page_cache_hit]
I0520 14:20:16.279779   47014 utils.go:90] Available ebpf hardware counters: [cpu_cycles cpu_instructions cache_miss task_clock_ms]
I0520 14:20:16.279786   47014 utils.go:103] Available cgroup metrics from cgroup: [cgroupfs_memory_usage_bytes cgroupfs_kernel_memory_usage_bytes cgroupfs_tcp_memory_usage_bytes cgroupfs_cpu
_usage_us cgroupfs_system_cpu_usage_us cgroupfs_user_cpu_usage_us cgroupfs_ioread_bytes cgroupfs_iowrite_bytes block_devices_used]
I0520 14:20:16.279796   47014 exporter.go:116] Initializing the GPU collector
I0520 14:20:16.373129   47014 watcher.go:67] Using in cluster k8s config
I0520 14:20:16.373139   47014 watcher.go:74] failed to get config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
I0520 14:20:16.373145   47014 watcher.go:126] k8s APIserver watcher was not enabled
I0520 14:20:16.373181   47014 prometheus_collector.go:92] Registered Container Prometheus metrics
I0520 14:20:16.373198   47014 prometheus_collector.go:97] Registered VM Prometheus metrics
I0520 14:20:16.373206   47014 prometheus_collector.go:101] Registered Node Prometheus metrics
I0520 14:20:16.373263   47014 model.go:177] Model Config PROCESS_TOTAL: {ModelType:Ratio ModelOutputType:DynPower TrainerName:SGDRegressorTrainer EnergySource:acpi SelectFilter: InitModelURL
: InitModelFilepath: IsNodePowerModel:false ProcessFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0520 14:20:16.373289   47014 model.go:94] Using Power Model Ratio
I0520 14:20:16.373298   47014 process_energy.go:113] Using the Ratio/DynPower Power Model to estimate Process Platform Power
I0520 14:20:16.373302   47014 process_energy.go:114] Process feature names: [cpu_instructions]
I0520 14:20:16.373309   47014 model.go:177] Model Config PROCESS_COMPONENTS: {ModelType:Ratio ModelOutputType:DynPower TrainerName:SGDRegressorTrainer EnergySource:intel_rapl SelectFilter: I
nitModelURL: InitModelFilepath: IsNodePowerModel:false ProcessFeatureNames:[] NodeFeatureNames:[] SystemMetaDataFeatureNames:[] SystemMetaDataFeatureValues:[]}
I0520 14:20:16.373318   47014 model.go:94] Using Power Model Ratio
I0520 14:20:16.373324   47014 process_energy.go:123] Using the Ratio/DynPower Power Model to estimate Process Component Power
I0520 14:20:16.373330   47014 process_energy.go:124] Process feature names: [cpu_instructions cpu_instructions cache_miss   gpu_compute_util]
I0520 14:20:16.373393   47014 exporter.go:175] starting to listen on 0.0.0.0:8888
I0520 14:20:16.373400   47014 exporter.go:181] Started Kepler in 176.451253ms
I0520 14:20:19.375761   47014 attacher.go:442] successfully get data with batch get and delete with 0 pids in 120.397µs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd1ce2d]

goroutine 110 [running]:
github.com/sustainable-computing-io/kepler/pkg/collector/stats/types.(*UInt64StatCollection).SumAllDeltaValues(...)
/kepler/pkg/collector/stats/types/types.go:135
github.com/sustainable-computing-io/kepler/pkg/collector/stats.(*NodeStats).CalcIdleEnergy(0xc000041900, {0x191a6b5, 0x12}, {0x191bff4, 0x13}, {0x1915db8, 0xf})
/kepler/pkg/collector/stats/node_stats.go:73 +0x6d
github.com/sustainable-computing-io/kepler/pkg/collector/stats.(*NodeStats).UpdateIdleEnergyWithMinValue(0xc000041900, 0x1?)
/kepler/pkg/collector/stats/node_stats.go:64 +0xb9
github.com/sustainable-computing-io/kepler/pkg/collector/energy.UpdateNodeIdleEnergy(0xc000041900)
/kepler/pkg/collector/energy/node_energy_collector.go:83 +0x4d
github.com/sustainable-computing-io/kepler/pkg/collector/energy.UpdateNodeEnergyMetrics(0xc000041900)
/kepler/pkg/collector/energy/node_energy_collector.go:105 +0xf3
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).UpdateNodeEnergyUtilizationMetrics(...)
/kepler/pkg/collector/metric_collector.go:143
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).UpdateEnergyUtilizationMetrics(0xc000041900)
/kepler/pkg/collector/metric_collector.go:134 +0x1b
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Update(0xc000041900)
/kepler/pkg/collector/metric_collector.go:109 +0x65
github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start.func1()
/kepler/pkg/manager/manager.go:74 +0x7b
created by github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start in goroutine 1
/kepler/pkg/manager/manager.go:66 +0x65
```

### What did you expect to happen?

No segfault

### How can we reproduce it (as minimally and precisely as possible)?

On a machine with a GPU:

```
# `make build` to build Kepler.
# `echo -n "true" > ./_output/ENABLE_PROCESS_METRICS` then try to run kepler locally on my server as shown below:
# _output/bin/kepler -enable-gpu=true -v "8" &
```

### Kepler image tag

<details>
Just using the main Kepler branch
</details>

### Kubernetes version

<details>

Wasn't running in K8s

</details>

### Cloud provider or bare metal

<details>
bare metal
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
RHEL 9.4
$ uname -a
Linux 3e5ef333d785 5.14.0-427.13.1.el9_4.x86_64

```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by maryamtahhan** [comment]
currently debugging

**Comment by maryamtahhan** [comment]
Can't replicate in a RHEL 9.4VM so closing as an anomaly for now. will reopen if I can reproduce it again.
