### ISSUE TITLE
SIGSEGV on Ubuntu 20

### ISSUE THREAD

**Issue by rad4day** [sustainable-computing-io/kepler#636]
**Describe the bug**

Currently, we are trying to run kepler in a Kubernetes v1.25.9 cluster and ran into a segmentation violation trying to start the exporter.

**To Reproduce**
1. Deploy Kepler via [helm chart](https://github.com/sustainable-computing-io/kepler-helm-chart/tree/af1bcd461ef0ed1d008e88a719138b37311885fa) to cluster
2. Wait for exporter to start
3. About one second after "Started Kepler in ...s" the segfault occurs.

**Expected behavior**
Kepler running or providing some useful information about what went wrong and failing gracefully.

**Server**
 - OS: Ubuntu 20 5.4.0-146-generic # 163-Ubuntu SMP Fri Mar 17 18:26:02 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
```
I0418 12:10:46.309045       1 gpu.go:43] Failed to init nvml, err: could not init nvml: error opening libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0418 12:10:46.312663       1 exporter.go:149] Kepler running on version: d1bfdc4
I0418 12:10:46.312718       1 config.go:169] using gCgroup ID in the BPF program: true
I0418 12:10:46.313033       1 config.go:170] kernel version: 5.4
I0418 12:10:46.313353       1 rapl_msr_util.go:129] failed to open path /dev/cpu/0/msr: no such file or directory
I0418 12:10:46.313684       1 power.go:64] Not able to obtain power, use estimate method
I0418 12:10:46.737341       1 exporter.go:167] Initializing the GPU collector
perf_event_open: No such file or directory
I0418 12:10:48.953114       1 bcc_attacher.go:98] failed to attach perf event cpu_cycles_hc_reader: failed to open bpf perf event: no such file or directory
perf_event_open: Invalid argument
I0418 12:10:48.953203       1 bcc_attacher.go:98] failed to attach perf event cpu_ref_cycles_hc_reader: failed to open bpf perf event: invalid argument
perf_event_open: No such file or directory
I0418 12:10:48.953280       1 bcc_attacher.go:98] failed to attach perf event cpu_instr_hc_reader: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I0418 12:10:48.953355       1 bcc_attacher.go:98] failed to attach perf event cache_miss_hc_reader: failed to open bpf perf event: no such file or directory
I0418 12:10:48.953376       1 bcc_attacher.go:135] Successfully load eBPF module with option: [-DNUM_CPUS=2]
I0418 12:10:48.977821       1 exporter.go:209] Started Kepler in 2.665289244s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xc19c4e]

goroutine 39 [running]:
github.com/sustainable-computing-io/kepler/pkg/cgroup.CCgroupV1StatManager.SetCGroupStat({{0xfed1a8?, 0xc000106f00?}}, {0xc000274b80, 0x40}, 0xc000146c48?)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/cgroup/cgroup_stats_linux.go:80 +0xae
github.com/sustainable-computing-io/kepler/pkg/collector/metric.(*ContainerMetrics).UpdateCgroupMetrics(0xc000251b80)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric/container_metric.go:274 +0x52
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateCgroupMetrics(0xc00016c5a0)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/container_cgroup_collector.go:45 +0x32d
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Update(0xc00016c5a0)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric_collector.go:116 +0x72
github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start.func1()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:64 +0x7b
created by github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:56 +0x6a
```

**Comment by jichenjc** [comment]
@rad4day can you help try image with kepler:0.4 which is stable version by updating the daemonset kepler exporter 
[cgroup.CCgroupV1StatManager.SetCGroupSta](https://github.com/sustainable-computing-io/kepler/releases)

@marceloamaral looks like this is new code `cgroup.CCgroupV1StatManager.SetCGroupSta`, not sure it's regression or something we haven't test before.. FYI

**Comment by marceloamaral** [comment]
Thank you for discovering this error. I had not noticed it previously.
I have create the PR #637 to address this issue.

**Comment by rad4day** [comment]
> @rad4day can you help try image with kepler:0.4 which is stable version by updating the daemonset kepler exporter [cgroup.CCgroupV1StatManager.SetCGroupSta](https://github.com/sustainable-computing-io/kepler/releases)

The release-0.4 tag works as expected. 👍🏻

**Comment by jichenjc** [comment]
The code has been merged and I think we can use latest to validate ..

**Comment by rad4day** [comment]
I just confirmed (PullPolicy: always, also manually deleted the latest tag on the servers) that the issue seems to be still present on `quay.io/...:latest`.

**Comment by rootfs** [comment]
@rad4day can you share the latest crash stack?

**Comment by rad4day** [comment]
```
$ kubectl logs -n monitoring kepler-exporter-7wn7f
I0423 20:28:08.234665       1 gpu.go:43] Failed to init nvml, err: could not init nvml: error opening libnvidia-ml.so.1: libnvidia-ml.so.1: cannot open shared object file: No such file or directory
I0423 20:28:08.238057       1 exporter.go:149] Kepler running on version: 56723f5
I0423 20:28:08.238142       1 config.go:169] using gCgroup ID in the BPF program: true
I0423 20:28:08.238290       1 config.go:170] kernel version: 5.4
I0423 20:28:08.238483       1 rapl_msr_util.go:129] failed to open path /dev/cpu/0/msr: no such file or directory
I0423 20:28:08.238899       1 power.go:77] Not able to obtain power, use estimate method
I0423 20:28:08.352261       1 exporter.go:167] Initializing the GPU collector
perf_event_open: No such file or directory
I0423 20:28:10.174923       1 bcc_attacher.go:98] failed to attach perf event cpu_cycles_hc_reader: failed to open bpf perf event: no such file or directory
perf_event_open: Invalid argument
I0423 20:28:10.175055       1 bcc_attacher.go:98] failed to attach perf event cpu_ref_cycles_hc_reader: failed to open bpf perf event: invalid argument
perf_event_open: No such file or directory
I0423 20:28:10.175136       1 bcc_attacher.go:98] failed to attach perf event cpu_instr_hc_reader: failed to open bpf perf event: no such file or directory
perf_event_open: No such file or directory
I0423 20:28:10.175235       1 bcc_attacher.go:98] failed to attach perf event cache_miss_hc_reader: failed to open bpf perf event: no such file or directory
I0423 20:28:10.175255       1 bcc_attacher.go:135] Successfully load eBPF module with option: [-DNUM_CPUS=2]
I0423 20:28:10.199020       1 exporter.go:209] Started Kepler in 1.961012937s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x100 pc=0xc19bee]

goroutine 50 [running]:
github.com/sustainable-computing-io/kepler/pkg/cgroup.CCgroupV1StatManager.SetCGroupStat({{0xfed148?, 0xc0000cd4c0?}}, {0xc000458e40, 0x40}, 0xc000112a50?)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/cgroup/cgroup_stats_linux.go:84 +0xae
github.com/sustainable-computing-io/kepler/pkg/collector/metric.(*ContainerMetrics).UpdateCgroupMetrics(0xc000500b40)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric/container_metric.go:274 +0x52
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateCgroupMetrics(0xc0001467e0)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/container_cgroup_collector.go:45 +0x32d
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Update(0xc0001467e0)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric_collector.go:116 +0x72
github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start.func1()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:64 +0x7b
created by github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:56 +0x6a
	
```
on
```
    Image:         quay.io/sustainable_computing_io/kepler:latest
    Image ID:      quay.io/sustainable_computing_io/kepler@sha256:5af0fbe3e67a023babc67caf059d63ba2bc6c47f65e4d2b771e713d6d7c5a2ed
```

Which seems to be at https://github.com/sustainable-computing-io/kepler/blob/56723f58342502452de0ba3c0c7f1e4b0ab4b2d7/pkg/cgroup/cgroup_stats_linux.go#L84

**Comment by rootfs** [comment]
@rad4day thanks for the info. Let me spin up an similar env and debug it.

**Comment by rad4day** [comment]
For both containerd and kubelet the following applies:
```
CPUAccounting=no
...
MemoryAccounting=yes
```
I get the same output for docker, even though docker.service does not exist.

**Comment by rad4day** [comment]
@rootfs 
```
$ systemctl show |grep Accounting
DefaultCPUAccounting=no
DefaultBlockIOAccounting=no
DefaultMemoryAccounting=yes
DefaultTasksAccounting=yes
```

**Comment by rootfs** [comment]
Thanks @rad4day 

`CPUAccounting` and `MemoryAccounting` have to be enabled to track the cgroup usage. If they are not enabled, we have to add additional checks in the code to prevent segv

**Comment by rootfs** [comment]
@rad4day The fix is in, can you try the latest image again? Thanks

**Comment by rad4day** [comment]
The image behaved as expected. Thank you.
