### ISSUE TITLE
GPU energy collection on VM crash 

### ISSUE THREAD

**Issue by sunya-ch** [sustainable-computing-io/kepler#883]
### What happened?

Got crashloopback from the following error.

```
goroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
main.finalizing()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/cmd/exporter.go:84 +0x1d
panic({0x157c420, 0x2407c60})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/sustainable-computing-io/kepler/pkg/collector/metric.(*NodeMetrics).CalcDynEnergy(0xc00059dc90?, {0x1745b68, 0x3}, {0x176fac4, 0x1})
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric/node_metric.go:402 +0x141
github.com/sustainable-computing-io/kepler/pkg/collector/metric.(*NodeMetrics).UpdateDynEnergy(0xc00078a200)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric/node_metric.go:394 +0x238
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateNodeEnergyMetrics(0xc00078a200)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/node_energy_collector.go:124 +0x165
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Initialize(0xc0001917c0?)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric_collector.go:80 +0x168
github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start(0xc0001aeb88)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:60 +0x25
main.main()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/cmd/exporter.go:242 +0x6b5
I0823 06:15:00.220233       1 exporter.go:87] Exiting..
```

### What did you expect to happen?

GPU energy should be collected.

### How can we reproduce it (as minimally and precisely as possible)?

Run Kepler on VM that has GPU enabled

### Anything else we need to know?

The following set of IdleCollection is called only when `IsSystemCollectionSupported` which is false on VM because RAPL is off but actually it is true for GPU because the GPU is bypassed. 

https://github.com/sustainable-computing-io/kepler/blob/9b82f25bcf43627c3993e745baf29ab024226986/pkg/collector/metric/node_metric.go#L347

https://github.com/sustainable-computing-io/kepler/blob/9b82f25bcf43627c3993e745baf29ab024226986/pkg/collector/node_energy_collector.go#L94

I will push the PR for fixing this. 

### Kepler image tag

<details>
latest-libbpf (ea58b7b3a12ac1e3a94d89f27bc1c04fe057b75e)
</details>

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Cloud provider or bare metal

<details>
IBM Cloud VPC
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

### Install tools

<details>

</details>

### Kepler deployment config

<details>

For on kubernetes:
```console
$ KEPLER_NAMESPACE=kepler

# provide kepler configmap
$ kubectl get configmap kepler-cfm -n ${KEPLER_NAMESPACE} 
# paste output here

# provide kepler deployment description
$ kubectl describe deployment kepler-exporter -n ${KEPLER_NAMESPACE} 
```

For standalone:
# put your Kepler command argument here

</details>

### Container runtime (CRI) and version (if applicable)

<details>

</details>

### Related plugins (CNI, CSI, ...) and versions (if applicable)

<details>

</details>

**Comment by sunya-ch** [comment]
After using the image after merged PR https://github.com/sustainable-computing-io/kepler/pull/884, now the above error has fixed and GetGPUPower is called. 

However, I got another error.

```
panic: runtime error: index out of range [11] with length 6

goroutine 164 [running]:
github.com/sustainable-computing-io/kepler/pkg/model/estimator/local.(*RatioPowerModel).getPowerByRatio(...)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/model/estimator/local/ratio.go:84
github.com/sustainable-computing-io/kepler/pkg/model/estimator/local.(*RatioPowerModel).GetGPUPower(0xc0003049a0, 0x1)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/model/estimator/local/ratio.go:177 +0x2bf
github.com/sustainable-computing-io/kepler/pkg/model.addEstimatedEnergy({0xc0003c5000, 0x54, 0xc0008ea1a0?}, 0x0?, 0x1)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/model/container_energy.go:194 +0x218
github.com/sustainable-computing-io/kepler/pkg/model.UpdateContainerEnergy(0xc000446300?, 0x0?)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/model/container_energy.go:139 +0x145
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).updateContainerEnergy(...)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/container_energy_collector.go:25
github.com/sustainable-computing-io/kepler/pkg/collector.(*Collector).Update(0xc000446300)
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/collector/metric_collector.go:121 +0x128
github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start.func1()
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:72 +0x7b
created by github.com/sustainable-computing-io/kepler/pkg/manager.(*CollectorManager).Start
	/opt/app-root/src/github.com/sustainable-computing-io/kepler/pkg/manager/manager.go:64 +0x6a
```

However, this might be fixed with some variable typo correction in GetGPUPower (`GpuDynPower ` to `GpuUsageMetric`).

**Comment by sunya-ch** [comment]
Fixed
